mysite/mystie/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('users.urls'))
]

mysite/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('user/<int:pk>/profile/$', views.profile, name='profile'),
    path('user/<int:pk>/profile/update/$', views.profile_update, name='profile_update'),
    path('user/<int:pk>/pwdchange/$', views.pwd_change, name='pwd_change'),
    path('logout/', views.logout, name='logout'),
    # path('user/int:<pk>/plan/detail/<int:planpk>/$', views.plan, name='plan'),
    path('plan/post/<int:pk>/$', views.post_plan, name='post_plan'),
    # grab matched data from the database
    path('matched_list/<int:pk>/$', views.matched_list, name='matched_list'),

    # delete the latest record
    #path('delete/detail/<int:pk>/$', views.delete, name='delete'),

    # what is hot
    path('whatishot/detail/<int:pk>/$', views.topone, name='topone'),

    #saxue
    path('search/',views.search,name='search'),
    path('search/detail', views.search_detail, name='search_detail'),

    path('user/<int:pk>/plan_list/$',views.plan_list,name='plan_list'),
    path('user/<int:pk>/plan/detail/<int:planpk>/$', views.plan_detail, name='plan_detail'),
    path('user/<int:pk>/plan/delete/<int:planpk>/$', views.plan_delete, name='plan_delete'),
    path('user/<int:pk>/plan/update/<int:planpk>/$', views.plan_update, name='plan_update'),
    path('user/<int:pk>/plan/update/action/<int:planpk>/$', views.plan_up, name='plan_up'),

    # sheng
    path('whatishot/detaillalaland/$', views.hotbybudget, name='hotbybudget'),
    # path('whatishot/currdata/$', views.hotbybudget, name = 'hotbybudget')
    path('whatishot/serve/$', views.serve, name='serve'),
    path('whatishot/map/$', views.map, name='map'),


    # confirm
    path('matched_list/<int:pk>/<int:myPlanPK>/confirm_information/$', views.confirm, name='confirm'),
    path('matched_list/<int:pk>/<int:myPlanPK>/confirm_1_information/$', views.confirm_1, name='confirm_1'),
    path('matched_list/<int:pk>/<int:myPlanPK>/confirm_2_information/$', views.confirm_2, name='confirm_2'),
    # reject
    path('matched_list/<int:pk>/<int:myPlanPK>/reject_information/$', views.reject, name='reject'),
path('matched_list/<int:pk>/<int:myPlanPK>/reject_1_information/$', views.reject_1, name='reject_1'),

path('matched_list/<int:pk>/<int:myPlanPK>/reject_2_information/$', views.reject_2, name='reject_2'),
    path('home/', views.home, name='home'),
path('homeLogin/', views.homeLogin, name='homeLogin'),
path('whatishot/<int:pk>/$', views.chart, name='chart'),

]

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):


   user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

   org = models.CharField(
       'Organization', max_length=128, blank=True)

   telephone = models.CharField(
       'Telephone', max_length=50, blank=True)

   mod_date = models.DateTimeField('Last modified', auto_now=True)


   class Meta:
       verbose_name = 'User Profile'

   def __str__(self):
        return "%s %s %s %s" % (self.user, self.org, self.telephone, self.mod_date)


class travel_Plan(models.Model):
    """ travel plan
    travelPlan(planID, country, city, budget, time, group size)
    """
    plan_id = models.AutoField(primary_key=True, verbose_name="plan_id")
    country=models.CharField('Country', max_length=128, blank=True)
    state=models.CharField('State', max_length=128, blank=True)
    city = models.CharField('City', max_length=128, blank=True)
    budget = models.IntegerField()
    start_time= models.DateField()
    end_time= models.DateField()
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='plan', null=True)
    status = models.CharField(max_length=10, default='unmatched', blank=False, null=False)


    class Meta:
        verbose_name = 'travel_Plan'
        unique_together = ('country', 'state', 'city', 'start_time', 'end_time', 'user')

    def __str__(self):
        result = []
        result.append(self.plan_id)
        result.append(self.country)
        result.append(self.state)
        result.append(self.city)
        result.append(self.budget)
        result.append(self.start_time)
        result.append(self.end_time)
        result.append(self.user)
        return str(result)

class match_list(models.Model):

   user_1 = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

   plan_id_1 = models.ForeignKey(travel_Plan, on_delete=models.CASCADE)

   user_2 = models.ForeignKey(UserProfile, related_name='%(class)s_requests_created', on_delete=models.CASCADE)

   plan_id_2 = models.ForeignKey(travel_Plan, related_name='%(class)s_requests_created', on_delete=models.CASCADE)

   status = models.CharField('status', max_length=10, blank=False, default='matched', null=False)

   class Meta:
       verbose_name = 'Match_List'
       abstract = False

   def __str__(self):
       result = []
       result.append(self.user_1)
       result.append(self.plan_id_1)
       result.append(self.user_2)
       result.append(self.plan_id_2)
       result.append(self.status)

       return str(result)


# class rating(match_list):
#
#     #
#     question1 = (
#         ('1', '1'),
#         ('2', '2'),
#         ('3', '3'),
#         ('4', '4'),
#         ('5', '5')
#     )
#
#     #
#     question2 = (
#         ('1', '1'),
#         ('2', '2'),
#         ('3', '3'),
#         ('4', '4'),
#         ('5', '5')
#     )
#
#     #
#     question3 = (
#         ('1', '1'),
#         ('2', '2'),
#         ('3', '3'),
#         ('4', '4'),
#         ('5', '5')
#     )
#
#     # blocked_users ?????
#
#     class Meta:
#         verbose_name = 'Rating'
#
#     def __str__(self):
#         return "%s %s %s" % (self.question1, self.question2, self.question3)

# class block_list():
#
#     # should we use foreign keys here?
#     #blocker_id =
#     #blocked_id =
#
#     class Meta:
#         verbose_name = 'Block_list'
#
#     def __str__(self):
#         return

mysite/users/views.py
from django.shortcuts import render, get_object_or_404,render_to_response
from django.contrib.auth.models import User
from .models import UserProfile,travel_Plan, match_list
from django.contrib import auth
from .forms import RegistrationForm, LoginForm,ProfileForm,PwdChangeForm,post_plan_Form
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse
from django.http import Http404
import datetime
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.db.models import Count
from django.db import connection
from django.views.decorators.csrf import csrf_protect
from django.http import JsonResponse
from django.db.models import Count, Q

import json
import pandas as pd
import os





# Create your views here.

def register(request):
    if request.method == 'POST':

        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password2']


            user = User.objects.create_user(username=username, password=password, email=email)


            user_profile = UserProfile(user=user)
            user_profile.save()

            return HttpResponseRedirect("/accounts/login/")

    else:
        form = RegistrationForm()

    return render(request, 'registration.html', {'form': form})


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = auth.authenticate(username=username, password=password)

            if user is not None and user.is_active:
               auth.login(request, user)
               me=User(username=username)
               my_profile=UserProfile(user=me)
               myplan=travel_Plan(user=my_profile)
               if myplan.status=='matched':
                  pass

               return HttpResponseRedirect(reverse('users:home'))

            else:

                 return render(request, 'login.html', {'form': form,
                               'message': 'Wrong password. Please try again.'})
    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})


@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect("/accounts/login/")



@login_required
def profile(request, pk):
   user = get_object_or_404(User, pk=pk)
   return render(request, 'profile.html', {'user': user})

@login_required
def profile_update(request, pk):
   user = get_object_or_404(User, pk=pk)
   user_profile = get_object_or_404(UserProfile, user=user)

   if request.method == "POST":
       form = ProfileForm(request.POST)

       if form.is_valid():
           user.first_name = form.cleaned_data['first_name']
           user.last_name = form.cleaned_data['last_name']
           user.save()

           user_profile.org = form.cleaned_data['org']
           user_profile.telephone = form.cleaned_data['telephone']
           user_profile.save()

           return HttpResponseRedirect(reverse('users:profile', args=[user.id]))
   else:
       default_data = {'first_name': user.first_name, 'last_name': user.last_name,
                        'org': user_profile.org, 'telephone': user_profile.telephone, }
       form = ProfileForm(default_data)

   return render(request, 'profile_update.html', {'form': form, 'user': user})


@login_required
def pwd_change(request, pk):
    user = get_object_or_404(User, pk=pk)

    if request.method == "POST":
        form = PwdChangeForm(request.POST)

        if form.is_valid():

            password = form.cleaned_data['old_password']
            username = user.username

            user = auth.authenticate(username=username, password=password)

            if user is not None and user.is_active:
                new_password = form.cleaned_data['password2']
                user.set_password(new_password)
                user.save()
                return HttpResponseRedirect("/accounts/login/")

            else:
                return render(request, 'pwd_change.html', {'form': form,
                                                                 'user': user,
                                                                 'message': 'Old password is wrong. Try again'})
    else:
        form = PwdChangeForm()

    return render(request, 'pwd_change.html', {'form': form, 'user': user})


@login_required
def post_plan(request, pk):
    # user_profile = get_object_or_404(UserProfile, pk=pk)
    # user = get_object_or_404(User, pk=pk)
    # travel_plan = get_object_or_404(travel_Plan,user=user)
    if request.method == 'POST':
        form = post_plan_Form(request.POST)
        if form.is_valid():
            user = User.objects.get(pk=pk)
            user_profile = UserProfile.objects.get(user=user)
            country = form.cleaned_data['country']
            state = form.cleaned_data['state']
            city = form.cleaned_data['city']
            budget = form.cleaned_data['budget']
            start_time = form.cleaned_data['start_time']
            end_time = form.cleaned_data['end_time']
            travel_plan = travel_Plan(user=user_profile, country=country, state=state, city=city, budget=budget,
                                      start_time=start_time, end_time=end_time)
            print(user_profile.user_id)
            try:
                print(travel_plan)
                travel_plan.save()
                # planid=travel_plan.plan_id
                # print(planid)
                myplan = travel_Plan.objects.raw(
                    '''SELECT * FROM users_travel_Plan WHERE user_id=%s ORDER BY plan_id DESC''', [user_profile.id])
                # return render(request, 'plan_list.html', {'travel_plan': travel_plan})
                # myplan = travel_Plan.objects.raw('''SELECT * FROM users_travel_Plan WHERE user_id=%s AND plan_id=%s ''', [user_profile.id,planid])
                print("test")
                print(travel_plan.plan_id)

                matched_plan = match_helper(user_profile.id, travel_plan.plan_id, -1)
                print(travel_plan.user)
                if matched_plan is not None:
                    match_list1 = match_list(user_1_id=travel_plan.user_id, plan_id_1_id=travel_plan.plan_id,
                                             user_2_id=matched_plan.user_id, plan_id_2_id=matched_plan.plan_id)
                    match_list2 = match_list(user_1_id=matched_plan.user_id, plan_id_1_id=matched_plan.plan_id,
                                             user_2_id=travel_plan.user_id, plan_id_2_id=travel_plan.plan_id)
                    match_list1.save()
                    match_list2.save()
                    plan_active = travel_Plan.objects.get(user=travel_plan.user, plan_id=travel_plan.plan_id)
                    plan_active.status = 'matched'
                    plan_active.save()
                    plan_passive = travel_Plan.objects.get(user=matched_plan.user, plan_id=matched_plan.plan_id)
                    plan_passive.status = 'matched'
                    plan_passive.save()

                # myplan = travel_Plan.objects.raw('''SELECT * FROM users_travel_Plan WHERE user_id=%s AND plan_id=%s ''', [user_profile.id,planid])
                return render(request, 'plan_list.html', {'plan_list': myplan})
                # return render(request, 'plan_detail.html', {'plan_list': myplan})
            except IntegrityError as e:
                # duplicate happens
                e = 'this data already exists in the database'
                return HttpResponse(e)
                # return render(request, 'post_plan.html', context={ 'form': form, 'e': e})
    else:
        form = post_plan_Form()
        # return render(request, 'post_plan.html', {'form':form,'travel_plan':travel_plan })
        return render(request, 'post_plan.html', {'form': form})

"""
@login_required
def plan(request, pk):
    user = get_object_or_404(User, pk=pk)
    user_profile = UserProfile.objects.get(user=user)

    try:
        # myplan = travel_Plan.objects.filter(user=user_profile).order_by('plan_id').last()
        myplan = travel_Plan.objects.raw('''SELECT * FROM users_travel_Plan WHERE user_id=%s''', [user_profile.id])
    except (travel_Plan.DoesNotExist):
        myplan = travel_Plan()
    return render(request, 'plan_list.html', {'travel_plan': myplan})
"""
#  -------------------------------------------------------------------------------------------------------------


@login_required
def plan_list(request,pk):
    user = get_object_or_404(User, pk=pk)
    user_profile = UserProfile.objects.get(user=user)
    try:
        myplan = travel_Plan.objects.filter(user=user_profile)
        # myplan = travel_Plan.objects.raw('''SELECT * FROM users_travel_Plan WHERE user_id=%s ORDER BY plan_id''', [user_profile.id])
    except (travel_Plan.DoesNotExist):
        myplan = None
    print(user_profile.id)
    print(user.id)
    if str(myplan) == '<QuerySet []>':
        myplan = ''
    return render(request, 'plan_list.html', {'plan_list': myplan})

@login_required
def plan_detail(request,pk,planpk):
    user = get_object_or_404(User, pk=pk)
    user_profile = UserProfile.objects.get(user=user)
    myplan=travel_Plan.objects.get(user=user_profile,pk=planpk)
    #myplan = travel_Plan.objects.raw('''SELECT * FROM users_travel_Plan WHERE plan_id=%s AND user_id=%s''', [planpk,user_profile.id])
    print(planpk)
    print(user_profile.id)
    print(user.id)
    return render(request, 'plan_detail.html', {'myplan': myplan})

@login_required
def plan_update(request,pk,planpk):
    user = get_object_or_404(User, pk=pk)

mysite/users/templates/base2.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="{% static 'css/interface.css' %}" rel="stylesheet"/>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: "Lato", sans-serif}
</style>
<body>

<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-black w3-card">
    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="call()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="{% url 'users:home'%}" class="w3-bar-item w3-button w3-padding-large">MeetByChance</a>
    <a href="{% url 'users:post_plan' user.id %}" class="w3-bar-item w3-button w3-padding-large">Post Plan</a>
    <a href="{% url 'users:plan_list' user.id %}" class="w3-bar-item w3-button w3-padding-large">My Plan</a>
    <a href="{% url 'users:matched_list' user.id %}" class="w3-bar-item w3-button w3-padding-large">My Match <!--span class="w3-badge w3-red">1</span--> </a>
      <a href="{% url 'users:search' %}" class="w3-bar-item w3-button w3-padding-large">Search</a>
      <div class="w3-dropdown-hover w3-hide-small">
      <button class="w3-padding-large w3-button" title="Setting">What is Hot <i class="fa fa-caret-down"></i></button>
      <div class="w3-dropdown-content w3-bar-block w3-card-4">
        <a href="{% url 'users:topone' user.id%}" class="w3-bar-item w3-button">Hot By Budget</a>
        <a href="{% url 'users:map' %}" class="w3-bar-item w3-button">Heat Map</a>
        <a href="{% url 'users:chart' user.id%}" class="w3-bar-item w3-button">Chart By City</a>
      </div>
    </div>
      <a href="{% url 'users:logout'%}" class="w3-bar-item w3-button w3-padding-large w3-right">LogOut</a>
      <div class="w3-dropdown-hover w3-hide-small w3-right">
      <button class="w3-padding-large w3-button" title="Setting">Account <i class="fa fa-caret-down"></i></button>
      <div class="w3-dropdown-content w3-bar-block w3-card-4">
        <a href="{% url 'users:profile' user.id%}" class="w3-bar-item w3-button">My Profile</a>
        <a href="{% url 'users:pwd_change' user.id%}" class="w3-bar-item w3-button">Change Password</a>
      </div>
    </div>


  </div>
</div>

<!-- Navbar on small screens (remove the onclick attribute if you want the navbar to always show on top of the content when clicking on the links) -->
<div id="navDemo" class="w3-bar-block w3-black w3-hide w3-hide-large w3-hide-medium w3-top" style="margin-top:46px">
    <a href="{% url 'users:home' %}" class="w3-bar-item w3-button w3-padding-large">HOME</a>
    <a href="{% url 'users:post_plan' user.id %}">Post Plan</a>
    <a href="{% url 'users:plan_list' user.id %}">My Plan</a>
    <a href="{% url 'users:matched_list' user.id %}">My Match</a>
    <a href="{% url 'users:search' %}">Search</a>
    <a href="{% url 'users:topone' user.id%}">What is Hot</a>
    <a href="{% url 'users:logout'%}">LogOut</a>
    <a href="{% url 'users:profile' user.id%}">Profile</a>
</div>

   {% block content %}{% endblock %}
<!-- Footer -->
<footer class="w3-container w3-padding-64 w3-center w3-opacity w3-light-grey w3-xlarge">
  <p class="w3-medium">Powered by Group37 CS411SP2019</a></p>
</footer>

</body>
</html>

mysite/users/templates/matched_list.html
{% extends 'base2.html' %}
{% load staticfiles %}



{% block content %}
{% load static  %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div  style="margin: 5% 10% ;" >
    <h2 >My Matched Plans</h2></div>
    {% if myplan_1.status != 'matched'%}
        {% if myplan_2.status != 'matched'  %}

            {% if myplan_3.status != 'matched'%}
                    <h4 class="fa" style="margin: 1% 12% ;">No Matched Plans yet...</h4>
                <br>
                <br> <br> <br>
            {% endif %}
        {% endif %}
    {% endif %}


{% if myplan_1.status == 'matched' %}
<div class="w3-table" style="margin: 5% 20% ;">
<h4>My first trip:</h4>
<ul id="trip_1">
    <table width="83%" >
        <tr>
            <th>matched_user_id: </th><th>{{ matched_user2_1.id}}</th> </tr>
        <tr> <th>matched_user_username: </th><th> {{ matched_user2_1.username }}</th></tr>
        <tr> <th>matched_user_email: </th><th>{{ matched_user2_1.email }}</th></tr>
        <tr>
            <th>
                plan_id:
            </th>
            <th>
                {{ matched_plan2_1.plan_id}}
            </th>
        </tr>
        <tr>
            <th>
                Country:
            </th>
            <th>
               {{ matched_plan2_1.country }}
            </th>
        </tr>
        <tr>
            <th>
              State:
            </th>
            <th>
               {{ matched_plan2_1.state }}
            </th>
        </tr>
        <tr>
            <th>
                City:
            </th>
            <th>
                {{ matched_plan2_1.city}}
            </th>
        </tr>
        <tr>
            <th>
               Budget:
            </th>
            <th>
               {{ matched_plan2_1.budget }}
            </th>
        </tr>
        <tr>
            <th>
               Start_time:
            </th>
            <th>
                {{matched_plan2_1.start_time  }}
            </th>
        </tr>
        <tr>
            <th>
               End_time:
            </th>
            <th>
                {{ matched_plan2_1.end_time }}
            </th>
        </tr>
        <tr>
            <th>
               My Status:
            </th>
            <th>

                {{ matched_plan_1.status}}
            </th>
        </tr>
        <tr>
            <th>
               My Partner's Status:
            </th>
            <th>

                {{ partner_matchList_1.status}}
            </th>
        </tr>

    </table>

</ul>
    <div style="width:400px;">
     <div style="float: left; width: 130px">
    <form action="{%  url 'users:confirm' user.id myplan_1.plan_id%}" method=''>
     <button type="submit">Confirm</button>
    </form>
     </div>
 <div style="float: left; width: 225px">
    <form action="{%  url 'users:reject' user.id myplan_1.plan_id %}" method=''>
      <button type="submit">Reject</button>
    </form>
 </div>
    </div>

</div>
{% endif %}

    {% if myplan_2.status == 'matched' %}
<div class="w3-table" style="margin: 5% 20% ;">
<h4>My second trip:</h4>
<ul id="trip_2">

        <table width="100%">
        <tr>
            <th>matched_user_id: </th><th>{{ matched_user2_2.id}}</th> </tr>
        <tr> <th>matched_user_username: </th><th> {{ matched_user2_2.username }}</th></tr>
        <tr> <th>matched_user_email: </th><th>{{ matched_user2_2.email }}</th></tr>
        <tr>
            <th>
                plan_id:
            </th>
            <th>
                {{ matched_plan2_2.plan_id}}
            </th>
        </tr>
        <tr>
            <th>
                Country:
            </th>
            <th>
               {{ matched_plan2_2.country }}
            </th>
        </tr>
        <tr>
            <th>
              State:
            </th>
            <th>
               {{ matched_plan2_2.state }}
            </th>
        </tr>
        <tr>
            <th>
                City:
            </th>
            <th>
                {{ matched_plan2_2.city}}
            </th>
        </tr>
        <tr>
            <th>
               Budget:
            </th>
            <th>
               {{ matched_plan2_2.budget }}
            </th>
        </tr>
        <tr>
            <th>
               Start_time:
            </th>
            <th>
                {{matched_plan2_2.start_time  }}
            </th>
        </tr>
        <tr>
            <th>
               End_time:
            </th>
            <th>
                {{ matched_plan2_2.end_time }}
            </th>
        </tr>
        <tr>
            <th>
               My Status:
            </th>
            <th>

                {{ matched_plan_2.status}}
            </th>
        </tr>
        <tr>
            <th>
               My Partner's Status:
            </th>
            <th>

                {{ matched_plan2_2.status}}
            </th>
        </tr>

    </table>

</ul>
    <div style="width:400px;">
     <div style="float: left; width: 130px">
    <form action="{%  url 'users:confirm_1' user.id myplan_2.plan_id %}" method=''>
     <button type="submit">Confirm</button>
    </form>
     </div>
 <div style="float: left; width: 225px">
    <form action="{%  url 'users:reject_1' user.id myplan_2.plan_id%}" method=''>
      <button type="submit">Reject</button>
    </form>

 </div>
    </div>

</div>
{% endif %}

     {% if myplan_3.status == 'matched' %}
<div class="w3-table" style="margin: 5% 20% ;">

<h4>My third trip:</h4>

{# the function doesn't work but keep it first   #}
<script>
    {#alert("dsafdsafds")#}
    checknull(travel_plan, matched_user, id){
        if (travel_plan == null || matched_user == null) {
            alert("1234")
            document.getElementById(id).children[0].style.display = "none"
        }
    }
</script>
<ul id="trip_3">


        <table width="100%">
        <tr>
            <th>matched_user_id: </th><th>{{ matched_user2_3.id}}</th> </tr>
        <tr> <th>matched_user_username: </th><th> {{ matched_user2_3.username }}</th></tr>
        <tr> <th>matched_user_email: </th><th>{{ matched_user2_3.email }}</th></tr>
        <tr>
            <th>
                plan_id:
            </th>
            <th>
                {{ matched_plan2_3.plan_id}}
            </th>
        </tr>
        <tr>
            <th>
                Country:
            </th>
            <th>
               {{ matched_plan2_3.country }}
            </th>
        </tr>
        <tr>
            <th>
              State:
            </th>
            <th>
               {{ matched_plan2_3.state }}
            </th>
        </tr>
        <tr>
            <th>
                City:
            </th>
            <th>
                {{ matched_plan2_3.city}}
            </th>
        </tr>
        <tr>
            <th>
               Budget:
            </th>
            <th>
               {{ matched_plan2_3.budget }}
            </th>
        </tr>
        <tr>
            <th>
               Start_time:
            </th>
            <th>
                {{matched_plan2_3.start_time  }}
            </th>
        </tr>
        <tr>
            <th>
               End_time:
            </th>
            <th>
                {{ matched_plan2_3.end_time }}
            </th>
        </tr>
        <tr>
            <th>
               My Status:
            </th>
            <th>

                {{ matched_plan_3.status}}
            </th>
        </tr>
        <tr>
            <th>
               My Partner's Status:
            </th>
            <th>

                {{ matched_plan2_3.status}}
            </th>
        </tr>
    </table>
</ul>
    <div style="width:400px;">
     <div style="float: left; width: 130px">
    <form action="{%  url 'users:confirm_2' user.id myplan_3.plan_id %}" method=''>
     <button type="submit">Confirm</button>
    </form>
     </div>
 <div style="float: left; width: 225px">
    <form action="{%  url 'users:reject_2' user.id myplan_3.plan_id %}" method=''>
      <button type="submit">Reject</button>
    </form>
 </div>
    </div>

</div>
    {% endif %}

{% endblock %}

mysite/users/templates/profile.html
{% extends 'base2.html' %}
{% load staticfiles %}
{% block css %}<link href="{% static 'css/other.css' %}" rel="stylesheet"/>{% endblock %}
{% block content %}
    <Title>My Profile</Title>


<h2 style="margin: 5% 10%;">My Profile</h2>

<div style="margin: 5% 30%;">

<ul>
    <table width="100%" class="w3-table">
        <tr>
            <th>Username: </th>
            <th>{{ user.username }}</th>
        </tr>
        <tr>
            <th>Email: </th>
            <th>{{ user.email }}</th>
        </tr>
        <tr>
            <th>
                First Name: </th>
            <th>{{ user.first_name }}
            </th>
        </tr>
        <tr>
            <th>Last Name: </th>
            <th>{{ user.last_name }}</th>
        </tr>
        <tr>
            <th>Organization:</th>
            <th>{{ user.profile.org }}</th>
        </tr>
        <tr>
            <th>Telephone: </th>
            <th>{{ user.profile.telephone }}</th>
        </tr>
    </table>

</ul>


{% if user.is_authenticated %}
    <form method="get" action="{% url 'users:profile_update' user.id %}">
     <p align="center">
    <button type="submit">Edit</button>
     </p>
    </form>
{% endif %}
</div>

{% endblock %}